### ISSUE TITLE
Extension doesn't work on MacOS Ventura

### ISSUE THREAD

**Issue by lucassarcanjo** [gabrieljsilva/insomnia-plugin-user-picker#1]
Hey @gabrieljsilva,

First of all, I would like to congratulate you on the fantastic work on this extension! That's exactly what I need, but I had trouble executing it on my Mac.

When running it with the console open, I received the following error message:

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/23055620/231209347-01c96716-5c3c-45c2-a413-0a6533a1ddd4.png">

It appears that there's a permission issue with writing a file in the Insomnia directory. On my Mac, the directory is located at:  `/Users/lucas/Library/Application Support/Insomnia/plugins/insomnia-plugin-user-picker/`. 

Usually, in OSX, applications store user data in a different folder, such as: `/Users/lucas/Library/Preferences/`. However, I'm not sure what the best place is to store this sensitive data, especially since it contains passwords. Storing passwords in plain text is also a security concern.

I was able to run the extension and use it properly by manually editing the `Persistor.js` file located at `/Users/lucas/Library/Application Support/Insomnia/plugins/insomnia-plugin-user-picker/src/persistor/persistor.js`. However, it would be good to have a solution for everyone who uses the package.

I can help with testing or even submit a pull request if you'd like. Thanks in advance!

**Comment by gabrieljsilva** [comment]
Hello @lucassarcanjo, thanks for the feedback.
I'm sorry for the problem, currently I don't have a Mac to test. I would be happy if you could open a Pull Request with a solution or viable alternative to JSON Persistor to avoid permission problems.

About passwords being saved in plain text, I am already working in a way to encrypt them before saving.

Again, thank you for the feedback.

**Comment by lucassarcanjo** [comment]
Ok! 

I'll work on that and let you know, thanks!

**Comment by gabrieljsilva** [comment]
I appreciate that :)

**Comment by gabrieljsilva** [comment]
Problem Fixed in MacOs and Windows
